name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Build Electron app
      run: npx electron-builder
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: naha-mc-helper-${{ github.ref_name }}
        path: |
          dist/
          dist-electron-fixed/
        retention-days: 30
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist-electron-fixed/*.exe
          dist-electron-fixed/*.blockmap
        body: |
          ## NAHA MC Helper ${{ github.ref_name }}
          
          ### What's New
          - Updated to Svelte 5 and Vite 7
          - Auto-updater functionality
          - Improved user interface
          - Bug fixes and performance improvements
          
          ### Installation
          1. Download the installer (NSIS) or portable version
          2. Run the setup file
          3. Follow the installation wizard
          
          ### Auto-Update
          The application will automatically check for updates and notify you when new versions are available.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        
    - name: Update version info
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
